version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pdfjs-dist"
      - dependency-name: "@hocuspocus/provider"
