packages:
  - examples/*
  - e2e-tests
  - apps/*
  - packages/**/*
  - shared/*

catalog:
  "@vitejs/plugin-vue": "^6.0.2"
  "typescript": "^5.9.2"
  "vite-plugin-dts": "~4.5.0"
  "vite-plugin-node-polyfills": "^0.24.0"
  "vite": "^7.2.7"
  "vitest": "^4.0.15"
  "vue": "^3.5.20"
