name: 💡 Feature request
description: Suggest a new capability or improvement
title: "feat: <short summary>"
labels: ["feature", "needs-triage"]

body:
  - type: checkboxes
    id: type
    attributes:
      label: Type
      options:
        - label: Feature
          required: true
        - label: Other
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the new feature or improvement
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior / Limitation
      description: What is the current limitation or missing capability?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should the feature do?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Example Use Case
      description: Provide a short example of how this feature would be used
      placeholder: |
        1. …
        2. …
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: SuperDoc Version
      placeholder: e.g. 0.14.3
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Extra information, related issues, or screenshots
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Checked for duplicates
          required: true
        - label: Added relevant labels
          required: false
