const PIXELS_PER_INCH = 96;
const CONTENT_HEIGHT_ALLOWANCE_INCHES = 0.05;
const CONTENT_HEIGHT_ALLOWANCE_IN_PX = PIXELS_PER_INCH * CONTENT_HEIGHT_ALLOWANCE_INCHES;
const DEFAULT_PAGE_HEIGHT_IN_PX = Math.round(11 * PIXELS_PER_INCH);
const DEFAULT_PAGE_WIDTH_IN_PX = Math.round(8.5 * PIXELS_PER_INCH);
const DEFAULT_PAGE_MARGINS_IN_PX = Object.freeze({
  top: PIXELS_PER_INCH * 1,
  bottom: PIXELS_PER_INCH * 1,
  left: PIXELS_PER_INCH * 1,
  right: PIXELS_PER_INCH * 1,
});
const BREAK_TOLERANCE_PX = 2.0;
const BINARY_BACKTRACK_STEPS = 12;
const DEFAULT_PAGE_BREAK_GAP_PX = 20;

export {
  PIXELS_PER_INCH,
  CONTENT_HEIGHT_ALLOWANCE_INCHES,
  CONTENT_HEIGHT_ALLOWANCE_IN_PX,
  DEFAULT_PAGE_HEIGHT_IN_PX,
  DEFAULT_PAGE_WIDTH_IN_PX,
  DEFAULT_PAGE_MARGINS_IN_PX,
  BREAK_TOLERANCE_PX,
  BINARY_BACKTRACK_STEPS,
  DEFAULT_PAGE_BREAK_GAP_PX,
};
