name: CI Checks [auto]

on:
  push:
    branches: [main, 'release/**']
  pull_request:
    branches: [main, 'release/**']
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run checks in parallel
        run: |
          npm run format:check &
          npm run lint &
          wait
      
      - name: Build
        run: npm run build
      
      - name: Test
        run: npm test
      
      - name: Check commits (PR only)
        if: github.event_name == 'pull_request'
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }}