name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0, 2.1)'
        required: true
        type: string
      from:
        description: 'Create from branch/tag (default: main)'
        required: false
        default: 'main'
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.from }}
          token: ${{ secrets.SUPERDOC_PAT }}
      
      - name: Create and push release branch
        run: |
          BRANCH="release/${{ inputs.version }}"
          
          # Create the branch
          git checkout -b "$BRANCH"
          
          # Push to origin
          git push origin "$BRANCH"
          
          echo "✅ Created $BRANCH from ${{ inputs.from }}"
          echo ""
          echo "What happens next:"
          echo "1. Semantic release will detect the new branch"
          echo "2. It will automatically publish the current version as stable"
          echo "3. Main branch will continue with next minor version"
          echo ""
          echo "NPM tags:"
          echo "- @latest: ${{ inputs.version }}.0"
          echo "- @next: next minor version previews"
