name: 🎯 Create Release Branch [manual]

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.21, 1.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUPERDOC_PAT }}
          fetch-depth: 0
      
      - name: Create release branch
        run: |
          BRANCH="release/v${{ inputs.version }}"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"
          echo "✅ Created $BRANCH from main"
      
      - name: Bump main to next minor
        run: |
          # Calculate next minor version
          IFS='.' read -r major minor <<< "${{ inputs.version }}"
          NEXT_MINOR="$major.$((minor + 1))"
          
          # Switch to main and create empty commit
          git checkout main
          git pull origin main
          git commit --allow-empty -m "feat: begin v${NEXT_MINOR} development"
          git push origin main
          
          echo "✅ Bumped main to v${NEXT_MINOR}.0-next.x"