name: Publish docs

on:
  push:
    branches: [documentation]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: documentation
        env:
          token: ${{ secrets.SUPERDOC_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        working-directory: docs/
        run: npm install

      - name: Build VitePress site
        working-directory: docs/
        run: npm run build

      - name: Copy CNAME for custom domain
        run: cp docs/CNAME docs/.vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
        env:
          GH_PAT: ${{ secrets.SUPERDOC_PAT }}
