name: Publish Superdoc Package to npm on Tag

on:
  push:
    branches:
      - publish-github-action
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      
      - name: Install deps
        run: |
          npm ci --workspaces
          cd packages/super-editor
          npm install
          cd ../superdoc
          npm install
          cd ../..

      - name: Publish
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: npm run publish
          version: npm run version --prerelease
          title: "New Superdoc pre-release version"
          commit: "Publish a new pre-release version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
