name: Publish Superdoc Package to npm on Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: |
          npm i
          cd packages/super-editor
          npm i
          cd ../superdoc
          npm i
          cd ../..

      - name: Update version
        run: |
          git config user.email "nick@harbourshare.com"
          git config user.name "Nick Bernal"
          cd packages/superdoc
          npm version patch
          cat package.json
          git add .
          git commit -m "Bump version"
          git push

      - name: Publish
        run: |
          cd packages/superdoc
          npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
