name: Reset develop branch versioning after merge to main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-develop-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main (full history)
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.SUPERDOC_PAT }}

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Detect merge or fast-forward from develop
        id: detect
        run: |
          from_develop=false

          # Fast-forward case: main HEAD now matches develop
          if [ "$(git rev-parse HEAD)" = "$(git rev-parse develop)" ]; then
            from_develop=true
          else
            # Merge-commit case: check second parent
            parents=($(git log -1 --pretty=%P))
            if [ "${#parents[@]}" -eq 2 ] && \
               git merge-base --is-ancestor "${parents[1]}" develop; then
              from_develop=true
            fi
          fi

          echo "from_develop=$from_develop" >> $GITHUB_OUTPUT

      - name: Checkout develop for bump
        if: steps.detect.outputs.from_develop == 'true'
        run: git checkout develop

      - name: Bump patch & reset next
        if: steps.detect.outputs.from_develop == 'true'
        id: bump
        run: |
          version=$(jq -r '.version' packages/superdoc/package.json)
          base=${version%-next.*}
          IFS='.' read -r major minor patch <<< "$base"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch-next.0"
          jq ".version = \"$new_version\"" packages/superdoc/package.json > tmp.json
          mv tmp.json packages/superdoc/package.json
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit & push bump
        if: steps.detect.outputs.from_develop == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/superdoc/package.json
          git commit -m "chore: bump version → ${{ steps.bump.outputs.new_version }}"
          git push origin develop
