name: PR check [auto]

on:
  pull_request:
    branches: ["main", "release/**"]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E tests
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SUPERDOC_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"ref": "main", "inputs": {"superdoc-branch": "${{ github.head_ref }}", "pull-request-url": "${{ github.event.pull_request.html_url }}"}}' \
            ${{ secrets.SD_TESTS_URL }}
