name: 📦 Release Stable [auto]

on:
  push:
    branches: ['release/**']
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: release-stable-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    uses: ./.github/workflows/test-suite.yml
    with:
      run-visual: true
      run-e2e: true
    secrets: inherit

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SUPERDOC_PAT }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build packages
        run: npm run build
      
      - name: Debug branch detection
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Git ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"

      - name: Release to latest channel
        env:
          GITHUB_TOKEN: ${{ secrets.SUPERDOC_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  # Simple addition: bump main to next minor after stable release
  bump-main:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUPERDOC_PAT }}
          ref: main
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Bump to next minor
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Get version from release branch name (e.g., release/v0.16 -> 0.17.0-next.0)
          BRANCH="${GITHUB_REF#refs/heads/release/v}"
          IFS='.' read -r MAJOR MINOR <<< "$BRANCH"
          NEXT_VERSION="$MAJOR.$((MINOR + 1)).0-next.0"
          
          # Update package.json
          cd packages/superdoc
          npm version "$NEXT_VERSION" --no-git-tag-version
          
          # Commit and push
          git add package.json
          git commit -m "chore: begin v$NEXT_VERSION development [skip ci]"
          git push origin main