name: 🚀 Release Next [auto]

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
      - '!**.md'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: release-next
  cancel-in-progress: true

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SUPERDOC_PAT }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install and build
        run: |
          npm ci
          npm run build
      
      - name: Release to next channel
        env:
          GITHUB_TOKEN: ${{ secrets.SUPERDOC_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release