name: Run E2E tests

on:
  workflow_call: # No inputs needed, but this needs to be here to be called by other workflows

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: cd packages/super-editor && npm ci

      - name: Build
        run: cd packages/super-editor && npm run build

      - name: Run E2E tests
        run: cd packages/super-editor && npm run test:e2e
