name: Test Example Apps [manual/auto]

on:
  push:
    branches: [main, 'release/**']
    paths:
      - 'examples/**'
      - 'packages/**/src/**'
  workflow_dispatch:
    inputs:
      update-screenshots:
        description: "Update screenshots"
        type: boolean
        default: false

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - name: Setup tests
        run: |
          cd examples/tests
          npm ci
          npx playwright install --with-deps
      
      - name: Run visual tests
        run: |
          cd examples/tests
          npm test ${{ inputs.update-screenshots && '-- --update-snapshots' || '' }}
      
      - name: Create PR with updates
        if: inputs.update-screenshots == true
        env:
          GH_TOKEN: ${{ secrets.SUPERDOC_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          BRANCH="visual-updates-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          git add -A
          git commit -m "chore: update visual snapshots" || exit 0
          git push origin "$BRANCH"
          
          gh pr create \
            --base ${{ github.ref_name }} \
            --title "chore: update visual snapshots" \
            --body "Automated visual test updates" \
            --label "visual-update"