name: 📚 Trigger Docs Update [auto]

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger-docs:
    runs-on: ubuntu-latest    
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Trigger documentation update
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SUPERDOC_PAT }}" \
            https://api.github.com/repos/Harbour-Enterprises/SuperDoc-Docs/dispatches \
            -d '{"event_type": "docs-update", "client_payload": {"version": "${{ github.event.release.tag_name }}"}}'